<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SysSeguridad2G05.DAL\SysSeguridad2G05.DAL.csproj" />
    <ProjectReference Include="..\SysSeguridad2G05.EN\SysSeguridad2G05.EN.csproj" />
  </ItemGroup>

</Project>
